"""
Django settings for Gen2PdfService project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ge=4jjm(iz*#gq(4_%wj9=ee!yxc-mgzrkhx!m&147y^&ej*(6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gen2PdfService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Gen2PdfService.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

SERVER_DATABASE = "pedigree"
SERVER_USER = "postgres"
SERVER_PASSWORD = "702633"
SERVER_HOST = "localhost"
SERVER_PORT = 5433

LOCAL_DATABASE = "local_pedigree"
LOCAL_USER = "postgres"
LOCAL_PASSWORD = "702633"
LOCAL_HOST = "localhost"
LOCAL_PORT = 5433

RESOURCE_PATH = os.path.join(os.path.abspath('.'), "resources")
PDF_OUTPUT_PATH = os.path.join(os.path.abspath('.'), "output")

MAX_ROW_STR = 26  # 每行最多的字符数  # 35
MAX_LINE = 40  # 行传每页最多的行数  # 47

MAX_LINE_TREE = 25  # 吊线图每页最多的行数

image_path = os.path.join(os.path.abspath('.'), "resources", "image")
IMAGE_PATH = image_path.replace('\\', '/')


PRESET_DOC_TYPE = ["凡例", "源流", "文献", "人物事迹", "家族事件", "公德榜", "附录", "后记"]

PERSON_ATTRIBUTE = ['id', 'family_name', 'name', 'zi', 'hao', 'sex', 'generation', 'ranknum', 'isliving', 'date_birth',
                    'date_dead', 'education', 'title_post', 'desc_living', 'desc_dead', 'father_id', 'zp_id']

PERSON_ATTRIBUTE_INDEX = [9, 10, 11, 12, 13, 14]

GENERATION_OPTIONS = {
    "father": "{0}{1}{2}；",  # 格式例：礼周 长 子
    "zi": "字：{}；",
    "hao": "号：{}；\n",

    "spouse": "娶妻：{}\n",
    "son": "子{}：{}\n",  # 格式例：子 二：兴元 兴知
    "daughter": "女{}：{}\n",  # 格式例：同上

    "date_birth": "生于{}；",
    "date_dead": "卒于{}；\n",

    "education": "教育程度：{}；",
    "title_post": "曾任：{}；\n",

    "desc_living": "{}\n",
    "desc_dead": "{}\n"
}
